name: fcs_pipeline
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - snakemake
  - r-base=4.3
  - bioconductor-flowcore
  - r-ggplot2
  - r-uwot
  - r-optparse
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - umap-learn
  - pip
  - pip:
      - FlowCal
      - fcswrite
